"""add_url_name_column

Revision ID: 9c0a1172df64
Revises: ed8ec88c52f9
Create Date: 2026-06-26 23:41:37.886935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c0a1172df64'
down_revision: Union[str, Sequence[str], None] = 'ed8ec88c52f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('name', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('urls', 'name')
    # ### end Alembic commands ###
